/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    SpendingPolicy: {
      address: "0xed1db453c3156ff3155a97ad217b3087d5dc5f6e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_agent",
              type: "address",
              internalType: "address",
            },
            {
              name: "_maxPerTx",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxPerDay",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "agent",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "allowedServices",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dailySpent",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lastResetDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxPerDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxPerTx",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recordSpend",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "remainingDailyBudget",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setAgent",
          inputs: [
            {
              name: "_agent",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPolicy",
          inputs: [
            {
              name: "_maxPerTx",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxPerDay",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "toggleService",
          inputs: [
            {
              name: "service",
              type: "string",
              internalType: "string",
            },
            {
              name: "allowed",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "PolicyUpdated",
          inputs: [
            {
              name: "maxPerTx",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxPerDay",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ServiceToggled",
          inputs: [
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "allowed",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendBlocked",
          inputs: [
            {
              name: "agent",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendRecorded",
          inputs: [
            {
              name: "agent",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
    BlindTokenVault: {
      address: "0x196dbcbb54b8ec4958c959d8949ebfe87ac2aaaf",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "activeTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "commitments",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isValid",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mintBatch",
          inputs: [
            {
              name: "_commitments",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintCommitment",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "redeem",
          inputs: [
            {
              name: "preimage",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "redeemed",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalMinted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalRedeemed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "TokenMinted",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenRedeemed",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "redeemer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 5,
    },
    AuditLog: {
      address: "0x05b4cb126885fb10464fdd12666feb25e2563b76",
      abi: [
        {
          type: "function",
          name: "entries",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "circuitId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "relay",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "entryCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntries",
          inputs: [
            {
              name: "offset",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limit",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct AuditLog.LogEntry[]",
              components: [
                {
                  name: "payloadHash",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "circuitId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "relay",
                  type: "address",
                  internalType: "address",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "log",
          inputs: [
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "circuitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "EntryLogged",
          inputs: [
            {
              name: "circuitId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "relay",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 5,
    },
    RelayRegistry: {
      address: "0x2a264f26859166c5bf3868a54593ee716aebc848",
      abi: [
        {
          type: "function",
          name: "deactivate",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getActiveRelays",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct RelayRegistry.Relay[]",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "url",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "pubkey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "pricePerHop",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRelay",
          inputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct RelayRegistry.Relay",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "url",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "pubkey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "pricePerHop",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "register",
          inputs: [
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerFor",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "relayCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "relayIndex",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "relays",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "update",
          inputs: [
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "RelayDeactivated",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RelayRegistered",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RelayUpdated",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 6,
    },
  },
  84532: {
    SpendingPolicy: {
      address: "0x65133639e5d57b2de6703fa701e8cb7565754e6d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_agent",
              type: "address",
              internalType: "address",
            },
            {
              name: "_maxPerTx",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxPerDay",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "agent",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "allowedServices",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dailySpent",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lastResetDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxPerDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxPerTx",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recordSpend",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "remainingDailyBudget",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setAgent",
          inputs: [
            {
              name: "_agent",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPolicy",
          inputs: [
            {
              name: "_maxPerTx",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxPerDay",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "toggleService",
          inputs: [
            {
              name: "service",
              type: "string",
              internalType: "string",
            },
            {
              name: "allowed",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "PolicyUpdated",
          inputs: [
            {
              name: "maxPerTx",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxPerDay",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ServiceToggled",
          inputs: [
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "allowed",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendBlocked",
          inputs: [
            {
              name: "agent",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendRecorded",
          inputs: [
            {
              name: "agent",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "service",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
    BlindTokenVault: {
      address: "0x1a78ef103b529c2a6fe8f3db97e1f7692a875092",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "activeTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "commitments",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isValid",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mintBatch",
          inputs: [
            {
              name: "_commitments",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintCommitment",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "redeem",
          inputs: [
            {
              name: "preimage",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "redeemed",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalMinted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalRedeemed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "TokenMinted",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenRedeemed",
          inputs: [
            {
              name: "commitment",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "redeemer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
    AuditLog: {
      address: "0x78f42b581f590a22ab42d26d35827586597b3dcc",
      abi: [
        {
          type: "function",
          name: "entries",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "circuitId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "relay",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "entryCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntries",
          inputs: [
            {
              name: "offset",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limit",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct AuditLog.LogEntry[]",
              components: [
                {
                  name: "payloadHash",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "circuitId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "relay",
                  type: "address",
                  internalType: "address",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "log",
          inputs: [
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "circuitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "EntryLogged",
          inputs: [
            {
              name: "circuitId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "relay",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
    RelayRegistry: {
      address: "0xa49a8a7e5727b0402e4590cb498b51da03a4d309",
      abi: [
        {
          type: "function",
          name: "deactivate",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getActiveRelays",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct RelayRegistry.Relay[]",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "url",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "pubkey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "pricePerHop",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRelay",
          inputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct RelayRegistry.Relay",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "url",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "pubkey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "pricePerHop",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "register",
          inputs: [
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerFor",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "relayCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "relayIndex",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "relays",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "update",
          inputs: [
            {
              name: "url",
              type: "string",
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "RelayDeactivated",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RelayRegistered",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RelayUpdated",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "url",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "pubkey",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "pricePerHop",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
